2024-08-29 07:26:03,587 Minimum price: 10, Maximum price: 350
2024-08-29 07:26:03,597 Preparing sklearn pipeline
2024-08-29 07:26:03,598 Fitting
Traceback (most recent call last):
  File "/Users/gerardolara/Project-Build-an-ML-Pipeline-Starter/src/train_random_forest/run.py", line 297, in <module>
    go(args)
  File "/Users/gerardolara/Project-Build-an-ML-Pipeline-Starter/src/train_random_forest/run.py", line 76, in go
    sk_pipe.fit(X_train, y_train)
  File "/Users/gerardolara/anaconda3/envs/mlflow-211c8fb974d6215abb361efdc7b6c4bd9a3e8dfd/lib/python3.10/site-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/Users/gerardolara/anaconda3/envs/mlflow-211c8fb974d6215abb361efdc7b6c4bd9a3e8dfd/lib/python3.10/site-packages/sklearn/pipeline.py", line 427, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/Users/gerardolara/anaconda3/envs/mlflow-211c8fb974d6215abb361efdc7b6c4bd9a3e8dfd/lib/python3.10/site-packages/sklearn/base.py", line 1145, in wrapper
    estimator._validate_params()
  File "/Users/gerardolara/anaconda3/envs/mlflow-211c8fb974d6215abb361efdc7b6c4bd9a3e8dfd/lib/python3.10/site-packages/sklearn/base.py", line 638, in _validate_params
    validate_parameter_constraints(
  File "/Users/gerardolara/anaconda3/envs/mlflow-211c8fb974d6215abb361efdc7b6c4bd9a3e8dfd/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 96, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'absolute_error', 'squared_error', 'poisson'}. Got 'mae' instead.